name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        run: make dev-docker CMD='make build'

      - name: Test
        run: make dev-docker CMD='make test'
